backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "character"
    label: "Character"
    folder: "src/pages/character"
    create: true
    slug: "{{name}}-{{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "character"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Faction", name: "faction", widget: "select", options: ["Autobot", "Decepticon"]}
      - {label: "Bot mode text", name: "alt-mode-text", widget: "text"}
      - {label: "Alt mode text", name: "bot-mode-text", widget: "text"}
      - {label: "Bot Image", name: "bot-image", widget: "image"}
      - {label: "Alt Image", name: "alt-image", widget: "image"}
      - {label: "Bot Attack Value", name: "bot-attack-value", widget: "number", default: 0, valueType: "int", min: 0, max: 10}
      - {label: "Alt Attack", name: "alt-attack", widget: "number", default: 0, valueType: "int", min: 0, max: 10}
      - {label: "Bot Defence Value", name: "bot-defence", widget: "number", default: 0, valueType: "int", min: 0, max: 10}
      - {label: "Alt Defence Value", name: "alt-defence", widget: "number", default: 0, valueType: "int", min: 0, max: 10}
      - {label: "Health Value", name: "health-defence", widget: "number", default: 0, valueType: "int", min: 0, max: 100}      
      - {label: "Stars", name: "stars", widget: "number", default: 0, valueType: "int", min: 0, max: 65}
      - {label: "Bot Keyword", name: "bot-keyword", widget: "select", options: ["Ranged", "Melee"]}
      - {label: "Alt Keyword", name: "alt-keyword", widget: "select", options: ["Ranged", "Melee"]}
      - {label: "Wave", name: "wave", widget: "select", options: ["Wave 1", "Rise Of The Combiners", "War for Cybertron Siege"]}
      - {label: "Rarity", name: "faction", widget: "select", options: ["Common", "Uncommon", "Rare", "Super Rare"]}
      - {label: "Upload Date", name: "date", widget: "datetime"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/characters/index.md"
        label: "Characters"
        name: "characters"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "characters-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}